name: Go CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #  Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3    # clones repo into the runner so the workflow can work with my code.

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.12'

    
    - name: Confirm Go version
      run: go version

    # Install dependencies
    - name: Download dependencies
      run: go mod tidy

    # Run unit tests
    - name: Run tests
      run: go test ./... -v

    # Lint code
    - name: Run linter (staticcheck)
      uses: dominikh/staticcheck-action@v1
      with:
        version: latest

    # Security analysis
    - name: Run security scan (gosec)
      uses: securego/gosec@master
      with:
        args: ./...

    # Deploy (example: push Docker image or call deploy script)
    - name: Deploy step (mock example)
      if: github.ref == 'refs/heads/main'
      run: echo "Deploying application (add something for depleymente (to do))"
