name: Go CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: mint-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3    # clones repo into the runner so the workflow can work with my code.

    # 2. Setup Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    # 3. Install dependencies
    - name: Download dependencies
      run: go mod tidy

    # 4. Run unit tests
    - name: Run tests
      run: go test ./... -v

    # 5. Lint code
    - name: Run linter (staticcheck)
      uses: dominikh/staticcheck-action@v1
      with:
        version: latest

    # 6. Security analysis
    - name: Run security scan (gosec)
      uses: securego/gosec@master
      with:
        args: ./...

    # 7. Deploy (example: push Docker image or call deploy script)
    - name: Deploy step (mock example)
      if: github.ref == 'refs/heads/main'
      run: echo "Deploying application (add your logic here)"
